### PR TITLE
fix(tinytorch): malformed-but-syntactically-valid progress/milestones JSON crashed

### PR DESCRIPTION
**Pull request by Shashank-Tripathi-07**
## Summary

Part of an ongoing testing effort tracked in #2046. Every state-file reader in `tito/commands/milestone.py` already guarded against invalid JSON (truncated, empty, binary garbage) via `except (json.JSONDecodeError, IOError)`, falling back to sensible empty defaults. It didn't guard against JSON that parses successfully but isn't the expected object shape, a bare list, string, or number instead of a dict. A bad merge conflict resolution, a manual edit, or any other process writing the wrong structure to `.tito/progress.json` or `.tito/milestones.json` produced valid JSON that then crashed with a raw `AttributeError` (`'list' object has no attribute 'get'`) at the read site or later downstream, instead of the graceful fallback the surrounding code clearly intends.

Fixes all 5 affected call sites: `_load_completed_module_numbers`, `_is_module_completed`, both copies of `_get_milestone_progress_data` (`MilestoneSystem` and `MilestoneCommand`), and the "what's next" progress read in the milestone run command. Each now validates the loaded data is a dict before using it, treating a wrong-shaped file the same as a decode failure.

Found while building a malformed-state-file test suite as a follow-up to the PyTorch cross-checking work (#2047, #2048).

## Test plan
- [x] `pytest tests/cli/test_release_regressions.py tests/milestones -q` passes locally (40 passed, 13 pre-existing unrelated failures on this Windows environment, confirmed present on `dev` before this change too)
- [x] New `tests/milestones/test_malformed_state_files.py` covers wrong-type JSON for both files across all affected call sites, plus a sanity check that genuinely-invalid JSON still falls back correctly and that valid data still round-trips normally
- [x] Confirmed the `AttributeError` reproduces on `dev` before the fix at each of the 5 sites, and no longer reproduces after

### CODE REVIEW

**Comment by Shashank-Tripathi-07** [comment]
Closing: this hardens against wrong-shaped-but-valid JSON, which requires the underlying file to already have been corrupted externally (manual edit, bad merge) — every normal tito write path always writes a correctly-shaped dict, so this never triggers through ordinary usage. Keeping the open-PR surface limited to bugs that occur in normal, everyday tinytorch/tito use.
